config/routes.rb
Spree::Core::Engine.routes.append do
  namespace :admin do
    resource :social, :only => [:edit, :update], :controller => "social"
  end
end

app/models/app_configuration_decorator.rb
Spree::AppConfiguration.class_eval do
  # Social Sharing Preferences
  preference :twitter_button, :boolean, :default => true
  preference :gplus_button, :boolean, :default => true
  preference :tumblr_button, :boolean, :default => false
  preference :pinterest_button, :boolean, :default => false
  preference :facebook_button, :boolean, :default => true
  preference :delicious_button, :boolean, :default => false
  preference :reddit_button, :boolean, :default => false
  preference :likes_only_on_fb, :boolean, :default => false

  preference :facebook_app_id, :string
  preference :facebook_app_secret, :string
end

app/controllers/spree/admin/social_controller.rb
module Spree
  module Admin
    class SocialController < Spree::Admin::BaseController
      def edit

      end

      def update
        params[:social].each do |provider, value|
          if value == '1'
            Spree::Config["#{provider}_button"] = true
          else
            Spree::Config["#{provider}_button"] = false
          end
        end
        if params[:likable] == '1'
          Spree::Config.likes_only_on_fb = true
        else
          Spree::Config.likes_only_on_fb = false
        end

        redirect_to edit_admin_social_path, :notice => t("social_sharing_settings_updated")
      end
    end
  end
end

app/helpers/spree/social_helper.rb
module Spree
  module SocialHelper
    def pin_it_button(product)
      return if product.images.empty?

      url = escape spree.product_url(product)
      media = escape absolute_image_url(product.images.first.attachment.url)
      description = escape product.name

      link_to("Pin It",
              "http://pinterest.com/pin/create/button/?url=#{url}&media=#{media}&description=#{description}",
              :class => "pin-it-button",
              "count-layout" => "none").html_safe
    end

    private

    def escape(string)
      URI.escape string, /[^#{URI::PATTERN::UNRESERVED}]/
    end

    def absolute_image_url(url)
      return url if url.starts_with? "http"
      request.protocol + request.host + url
    end
  end
end

app/views/spree/admin/shared/_configurations_menu_social_products.html.erb
<tr>
  <td><%= link_to t("social_sharing_buttons"), edit_admin_social_path %></td>
  <td><%= t("social_sharing_buttons_description") %></td>
</tr>

app/views/spree/admin/social/_form.html.erb
<%= form_tag admin_social_path, :method => :put do %>
  <ul class="social_list">
    <li>
      <%= image_tag 'social/twitter_16.png' %>
      <%= label_tag 'social[twitter]', 'Twitter', :class => 'first' %>
      <%= hidden_field_tag 'social[twitter]', '0' %>
      <%= check_box_tag 'social[twitter]', '1', Spree::Config.twitter_button %>
    </li>
    <li>
      <%= image_tag 'social/facebook_16.png' %>
      <%= label_tag 'social[facebook]', 'Facebook' %>
      <%= hidden_field_tag 'social[facebook]', '0' %>
      <%= check_box_tag 'social[facebook]', '1', Spree::Config.facebook_button %>
    </li>
    <li>
      <%= image_tag 'social/pinterest_16.png' %>
      <%= label_tag 'social[pinterest]', 'Pinterest' %>
      <%= hidden_field_tag 'social[pinterest]', '0' %>
      <%= check_box_tag 'social[pinterest]', '1', Spree::Config.pinterest_button %>
    </li>
    <li>
      <%= image_tag 'social/google_plus_16.png' %>
      <%= label_tag 'social[gplus]', 'Google Plus' %>
      <%= hidden_field_tag 'social[gplus]', '0' %>
      <%= check_box_tag 'social[gplus]', '1', Spree::Config.gplus_button %>
    </li>
    <li>
      <%= image_tag 'social/delicious_16.png' %>
      <%= label_tag 'social[delicious]', 'Delicious' %>
      <%= hidden_field_tag 'social[delicious]', '0' %>
      <%= check_box_tag 'social[delicious]', '1', Spree::Config.delicious_button %>
    </li>
    <li>
      <%= image_tag 'social/reddit_16.png' %>
      <%= label_tag 'social[reddit]', 'Reddit' %>
      <%= hidden_field_tag 'social[reddit]', '0' %>
      <%= check_box_tag 'social[reddit]', '1', Spree::Config.reddit_button %>
    </li>
    <li>
      <%= image_tag 'social/tumblr_16.png' %>
      <%= label_tag 'social[tumblr]', 'Tumblr' %>
      <%= hidden_field_tag 'social[tumblr]', '0' %>
      <%= check_box_tag 'social[tumblr]', '1', Spree::Config.tumblr_button %>
    </li>
    <li>
      <%= label_tag 'likable', t(:products_likable) %>
      <%= hidden_field_tag 'likable', '0' %>
      <%= check_box_tag 'likable', '1', Spree::Config.likes_only_on_fb %>
    </li>
  </ul>

  <div id="social_actions">
    <%= submit_tag 'Update' %>
  </div>
<% end %>

app/views/spree/admin/social/edit.html.erb
<h1><%= t("social_sharing_buttons") %></h1>
<div class="social_sharing_form">
  <p><%= t("social_sharing_settings_description") %></p>
  <%= render "form" %>
</div>

app/views/spree/shared/_facebook_status.html.erb
<% if flash[:notice] %>
  <% one = @order.line_items.first %>
  <% product = one.variant.product %>
  <script src='http://connect.facebook.net/fr_FR/all.js'></script>
  <p id='msg'></p>
  <script>
    if(window !== window.top){
      FB.init({
        appId      : "<%= Spree::Config.facebook_app_id %>", // App ID
        channelUrl : '//www.spreeworks.com/channel.html', // Channel File
        status     : true, // check login status
        cookie     : true, // enable cookies to allow the server to access the session
        xfbml      : true  // parse XFBML
      });


    function postToFeed() {

      var obj = {
        method: 'feed',
        link: '<%= product_url(product) %>',
        picture: '<%= "http://#{Spree::Config.site_url}/spree/products/#{product.images.first.id}/product/#{product.images.first.attachment_file_name}" %>',
        name: '<%= product.name %>',
        description: '<%= product.description %>',
        caption: 'Boutique <%= Spree::Config.site_name %>',
        message: "J'ai achete <%= one.quantity %> <%= product.name %> sur <%= Spree::Config.site_name %> !"
      };

      function callback(response) {
        if (response && response.post_id) {
          if(confirm('Le status a ete publie, voulez-vous etre redirige vers ce dernier ?')){
            FB.api('/me', function(response2) {
              link = "http://facebook.com/"+response2.name.toLowerCase().replace(" ", ".")+"/posts/"+response['post_id'].replace(/[0-9]+_/g, '');
              window.open(link);
            });
          }
        }else {
          alert('Post was not published.');
        } 
      }

      FB.ui(obj, callback);
    }

    postToFeed();
  }
  </script>
<% end %>

app/views/spree/shared/_social_buttons.html.erb
<div id="social_nav">
  <h6>BOOKMARK OR SHARE THIS</h6>
  <ul>
    <% if Spree::Config.twitter_button %>
      <li class="twitter">
        <%= render :partial => 'spree/social/twitter' %>
      </li>
    <% end %>
    <% if Spree::Config.pinterest_button %>
      <li class="pinterest">
        <%= render :partial => 'spree/social/pinterest' %>
      </li>
    <% end %>
    <% if Spree::Config.reddit_button %>
      <li class="reddit">
        <%= render :partial => 'spree/social/reddit' %>
      </li>
    <% end %>
    <% if Spree::Config.tumblr_button %>
      <li class="tumblr">
        <%= render :partial => 'spree/social/tumblr' %>
      </li>
    <% end %>
    <% if Spree::Config.delicious_button %>
      <li class="delicious">
        <%= render :partial => 'spree/social/delicious' %>
      </li>
    <% end %>
    <% if Spree::Config.gplus_button %>
      <li class="gplus">
        <%= render :partial => 'spree/social/gplus' %>
      </li>
    <% end %>
  </ul>
  <ul class="facebook-like-button">
    <% if Spree::Config.facebook_button %>
      <li class="facebook">
        <%= render :partial => 'spree/social/facebook' %>
      </li>
    <% end %>
  </ul>
</div>

app/views/spree/social/_async_loading_facebook.html.erb
<div id="fb-root"></div>
<script type="text/javascript">
	window.fbAsyncInit = function() {
	  FB.init({
	    appId      : "<%= Spree::Config.facebook_app_id %>", // App ID
	    channelUrl : '//www.spreeworks.com/channel.html', // Channel File
	    status     : true, // check login status
	    cookie     : true, // enable cookies to allow the server to access the session
	    xfbml      : true  // parse XFBML
	  });
	};
</script>

app/views/spree/social/_delicious.html.erb
<a href="http://www.delicious.com/save" onclick="window.open('http://www.delicious.com/save?v=5&noui&jump=close&url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title), 'delicious','toolbar=no,width=550,height=550'); return false;"><img src="/assets/social/delicious.png" height="19" width="19" alt="Delicious" />
</a>

app/views/spree/social/_facebook.html.erb
<% unless Spree::Config.facebook_app_id.nil? %>
  <% content_for :head do %>
    <meta property="og:title" content="<%= @product.name %>" />
    <meta property="og:type" content="product" />
    <meta property="og:url" content="<%= product_url(@product) %>" />
    <meta property="og:image" content="<%= "http://#{Spree::Config.site_url}/spree/products/#{@product.images.first.id}/product/#{@product.images.first.attachment_file_name}" %>" />
    <meta property="og:description" content="<%= @product.description %>" />
    <meta property="fb:app_id" content="<%= Spree::Config.facebook_app_id %>" />
  <% end %>

    <script src='http://connect.facebook.net/fr_FR/all.js'></script>
    <p><a onclick='postToFeed(); return false;' style="cursor:pointer;background-image:url('/assets/social/share_fb.png');width:64px;height:24px;display:block;"></a></p>
    <p id='msg'></p>
  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : "<%= Spree::Config.facebook_app_id %>", // App ID
        channelUrl : '//www.spreeworks.com/channel.html', // Channel File
        status     : true, // check login status
        cookie     : true, // enable cookies to allow the server to access the session
        xfbml      : true  // parse XFBML
      });
    };


    function postToFeed() {

      var obj = {
        method: 'feed',
        link: '<%= product_url(@product) %>',
        picture: '<%= "http://#{Spree::Config.site_url}/spree/products/#{@product.images.first.id}/product/#{@product.images.first.attachment_file_name}" %>',
        name: '<%= @product.name %>',
        caption: '<%= @product.images.first.attachment_file_name %>',
        description: '<%= @product.description %>'
      };

      function callback(response) {
        if (response && response.post_id) {
          if(confirm('Le status a ete publie, voulez-vous etre redirige vers ce dernier ?')){
            FB.api('/me', function(response2) {
              link = "http://facebook.com/"+response2.name.toLowerCase().replace(" ", ".")+"/posts/"+response['post_id'].replace(/[0-9]+_/g, '');
              window.top.location.replace(link);
            });
          }
        }else {
          alert('Post was not published.');
        } 
      }

      FB.ui(obj, callback);
    }

    // Load the SDK Asynchronously
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/fr_FR/all.js#xfbml=1&appId=<%= Spree::Config.facebook_app_id %>";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  </script>
  <div class="fb-like" data-send="true" data-width="470" data-show-faces="false" data-font="segoe ui" data-href='<%= "http://#{Spree::Config.site_url}/products/#{@product.permalink}" %>'></div>
<% end %>

app/views/spree/social/_facebook_on_products.html.erb
<% content_for :head do %>
	<meta property="og:title" content="<%= product.name %>" />
	<meta property="og:type" content="product" />
	<meta property="og:url" content="<%= product_url(product) %>" />
	<meta property="og:image" content="<%= "http://#{Spree::Config.site_url}/spree/products/#{product.images.first.id}/product/#{product.images.first.attachment_file_name}" %>" />
	<meta property="og:description" content="<%= product.description %>" />
	<meta property="fb:app_id" content="<%= Spree::Config.facebook_app_id %>" />
<% end %>

<div class="facebook-like">
	<% if Spree::Config.likes_only_on_fb %>
  	<script>
      if(window !== window.top){
    		(function(d, s, id) {
    			var js, fjs = d.getElementsByTagName(s)[0];
    			if (d.getElementById(id)) return;
    			js = d.createElement(s); js.id = id;
    			js.src = "//connect.facebook.net/fr_FR/all.js#xfbml=1&appId=<%= Spree::Config.facebook_app_id %>";
    			fjs.parentNode.insertBefore(js, fjs);
    		}(document, 'script', 'facebook-jssdk'));
      }
  	</script>
  <% else %>
    <script>
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/fr_FR/all.js#xfbml=1&appId=<%= Spree::Config.facebook_app_id %>";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    </script>
  <% end %>
	<div class="fb-like" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false" data-font="segoe ui" data-href="<%= product_url(product) %>"></div>
</div>

app/views/spree/social/_gplus.html.erb
<g:plusone size="medium"></g:plusone>

<!-- Place this render call where appropriate -->
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>

app/views/spree/social/_pinterest.html.erb
<%= pin_it_button(@product) %>
<script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>

app/views/spree/social/_reddit.html.erb
<a href="http://www.reddit.com/submit" onclick="window.location = 'http://www.reddit.com/submit?url=' + encodeURIComponent(window.location); return false"> <img src="http://www.reddit.com/static/spreddit1.gif" alt="submit to reddit" border="0" /> </a>

app/views/spree/social/_tumblr.html.erb
<a href="http://www.tumblr.com/share" title="Share on Tumblr" style="display:inline-block; text-indent:-9999px; overflow:hidden; width:81px; height:20px; background:url('http://platform.tumblr.com/v1/share_1.png') top left no-repeat transparent;">Share on Tumblr</a>

app/views/spree/social/_twitter.html.erb
<a href="https://twitter.com/share" class="twitter-share-button" data-count="none">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>